Vagrant::Config.run do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.vm.network :hostonly, '33.33.33.33'
  config.ssh.port = 22 # default SSH port

  config.ssh.username = 'vagrant' # default username

end
